config/routes.rb
Rails.application.routes.draw do
  resources :appointments

  resources :pets

  resources :customers

  resources :doctors

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :Pet
  belongs_to :Customer
  belongs_to :Doctor
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:next_appointment_date, :visit_purpose, :Pet_id, :Customer_id, :Doctor_id)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :next_appointment_date %><br>
    <%= f.datetime_select :next_appointment_date %>
  </div>
  <div class="field">
    <%= f.label :visit_purpose %><br>
    <%= f.text_field :visit_purpose %>
  </div>
  <div class="field">
    <%= f.label :Pet_id %><br>
    <%= f.text_field :Pet_id %>
  </div>
  <div class="field">
    <%= f.label :Customer_id %><br>
    <%= f.text_field :Customer_id %>
  </div>
  <div class="field">
    <%= f.label :Doctor_id %><br>
    <%= f.text_field :Doctor_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<h1>Listing appointments</h1>

<table>
  <thead>
    <tr>
      <th>Next appointment date</th>
      <th>Visit purpose</th>
      <th>Pet</th>
      <th>Customer</th>
      <th>Doctor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.next_appointment_date %></td>
        <td><%= appointment.visit_purpose %></td>
        <td><%= appointment.Pet.name %></td>
        <td><%= appointment.Pet.Customer.name %></td>
        <td><%= appointment.Doctor.name %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Next appointment date:</strong>
  <%= @appointment.next_appointment_date %>
</p>

<p>
  <strong>Visit purpose:</strong>
  <%= @appointment.visit_purpose %>
</p>

<p>
  <strong>Pet:</strong>
  <%= @appointment.Pet %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @appointment.Customer %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @appointment.Doctor %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>